#!/usr/bin/env bash
# Generates a Meson cross-compilation file for iOS device (arm64).
# Usage: gen-cross-file.sh <output-path> [ios-min-version] [pkgconfig-dir]
#
# Must be run on macOS with Xcode + iOS SDK installed (xcrun available).
# All native GTK-stack dependencies (glib, cairo, pango, ...) reuse this.
#
# pkgconfig-dir: directory Meson/pkg-config should search for .pc files.
#   - Omit (default) to point at a nonexistent dir, which isolates the build
#     from host (Homebrew) libraries — correct when building a base library
#     like GLib that has no in-prefix dependencies.
#   - Pass the shared install prefix's lib/pkgconfig when building libraries
#     that must find earlier ones already installed there (cairo, pango, ...).
set -euo pipefail

OUT="${1:?Usage: gen-cross-file.sh <output-path> [ios-min-version] [pkgconfig-dir]}"
IOS_MIN="${2:-17.0}"
PKGCONFIG_DIR="${3:-}"
# IOS_SDK env selects the Apple SDK: 'iphoneos' (device, default) or
# 'iphonesimulator'. The simulator uses a different SDK and a different
# clang minimum-version flag.
IOS_SDK="${IOS_SDK:-iphoneos}"
if [ "${IOS_SDK}" = "iphonesimulator" ]; then
  MIN_FLAG="-mios-simulator-version-min=${IOS_MIN}"
else
  MIN_FLAG="-mios-version-min=${IOS_MIN}"
fi

echo "[gen-cross-file] Resolving iOS SDK path via xcrun..."
SDKROOT="$(xcrun --sdk "${IOS_SDK}" --show-sdk-path)"
echo "[gen-cross-file] SDKROOT=${SDKROOT}"
echo "[gen-cross-file] iOS min version=${IOS_MIN}"

# Optional: EXE_WRAPPER env — path to a wrapper able to execute target
# binaries (simulator builds only; see sim-run.sh). Enables running
# g-ir-scanner dumpers and other target executables during the build.
EXE_WRAPPER="${EXE_WRAPPER:-}"

CC_PATH="$(xcrun --sdk "${IOS_SDK}" --find clang)"
CXX_PATH="$(xcrun --sdk "${IOS_SDK}" --find clang++)"

# Compiler WRAPPERS with the target flags baked in. Tools that take the
# compiler from the cross file but not its [built-in options] c_args —
# notably g-ir-scanner, which preprocesses/compiles/links its dumper via
# the CC env var — would otherwise invoke bare clang without -isysroot
# and fail with "time.h not found". The duplicate flags for regular
# meson targets (which also pass c_args) are harmless.
WRAP_DIR="$(cd "$(dirname "${OUT}")" && pwd)"
CC_WRAP="${WRAP_DIR}/ios-cc-${IOS_SDK}.sh"
CXX_WRAP="${WRAP_DIR}/ios-cxx-${IOS_SDK}.sh"
printf '#!/bin/bash\nexec "%s" -arch arm64 -isysroot "%s" %s "$@"\n' \
  "${CC_PATH}" "${SDKROOT}" "${MIN_FLAG}" > "${CC_WRAP}"
printf '#!/bin/bash\nexec "%s" -arch arm64 -isysroot "%s" %s "$@"\n' \
  "${CXX_PATH}" "${SDKROOT}" "${MIN_FLAG}" > "${CXX_WRAP}"
chmod +x "${CC_WRAP}" "${CXX_WRAP}"
AR_PATH="$(xcrun --sdk "${IOS_SDK}" --find ar)"
STRIP_PATH="$(xcrun --sdk "${IOS_SDK}" --find strip)"
echo "[gen-cross-file] clang=${CC_PATH}"

# Resolve the pkg-config search dir. Empty -> isolation (nonexistent) dir.
if [ -n "${PKGCONFIG_DIR}" ]; then
  PC_DIR="${PKGCONFIG_DIR}"
else
  PC_DIR="${SDKROOT}/nonexistent-pkgconfig"
fi
echo "[gen-cross-file] pkg_config_libdir=${PC_DIR}"

cat > "${OUT}" <<EOF
# Auto-generated by gen-cross-file.sh — iOS device arm64
[constants]
sdkroot = '${SDKROOT}'
ios_min = '${MIN_FLAG}'
common_flags = ['-arch', 'arm64', '-isysroot', sdkroot, ios_min]

[binaries]
c = '${CC_WRAP}'
cpp = '${CXX_WRAP}'
objc = '${CC_WRAP}'
objcpp = '${CXX_WRAP}'
ar = '${AR_PATH}'
strip = '${STRIP_PATH}'
pkg-config = 'pkg-config'
$( [ -n "${EXE_WRAPPER}" ] && echo "exe_wrapper = ['bash', '${EXE_WRAPPER}']" )

[built-in options]
c_args = common_flags
cpp_args = common_flags
objc_args = common_flags
objcpp_args = common_flags
c_link_args = common_flags
cpp_link_args = common_flags
objc_link_args = common_flags
objcpp_link_args = common_flags

[properties]
# iOS is a cross target; disable anything that tries to run target binaries.
needs_exe_wrapper = true
# NOTE: deliberately NOT setting 'sys_root'. Meson maps sys_root to
# PKG_CONFIG_SYSROOT_DIR, which prepends the SDK path to every -I/-L in our
# .pc files (e.g. libpng's -I<prefix>/include becomes
# -I<SDK><prefix>/include -> nonexistent), breaking dependent builds. The
# compiler already gets the SDK sysroot via -isysroot in the flags below,
# which is sufficient for finding SDK system headers/libraries.
# Prevent Meson/pkg-config from discovering host (macOS/Homebrew) libraries
# during the cross build. When building a base library this points at a
# nonexistent dir (isolation); when building dependent libraries it points
# at the shared prefix so earlier libraries are found.
pkg_config_libdir = '${PC_DIR}'

[host_machine]
system = 'darwin'
subsystem = 'ios'
kernel = 'xnu'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
EOF

echo "[gen-cross-file] Wrote cross file to ${OUT}:"
echo "-------------------------------------------"
cat "${OUT}"
echo "-------------------------------------------"
