#!/usr/bin/env bash
# Generates a Meson cross-compilation file for iOS device (arm64).
# Usage: gen-cross-file.sh <output-path> [ios-min-version]
#
# Must be run on macOS with Xcode + iOS SDK installed (xcrun available).
# All native GTK-stack dependencies (glib, cairo, pango, ...) reuse this.
set -euo pipefail

OUT="${1:?Usage: gen-cross-file.sh <output-path> [ios-min-version]}"
IOS_MIN="${2:-17.0}"

echo "[gen-cross-file] Resolving iOS SDK path via xcrun..."
SDKROOT="$(xcrun --sdk iphoneos --show-sdk-path)"
echo "[gen-cross-file] SDKROOT=${SDKROOT}"
echo "[gen-cross-file] iOS min version=${IOS_MIN}"

CC_PATH="$(xcrun --sdk iphoneos --find clang)"
CXX_PATH="$(xcrun --sdk iphoneos --find clang++)"
AR_PATH="$(xcrun --sdk iphoneos --find ar)"
STRIP_PATH="$(xcrun --sdk iphoneos --find strip)"
echo "[gen-cross-file] clang=${CC_PATH}"

cat > "${OUT}" <<EOF
# Auto-generated by gen-cross-file.sh — iOS device arm64
[constants]
sdkroot = '${SDKROOT}'
ios_min = '-mios-version-min=${IOS_MIN}'
common_flags = ['-arch', 'arm64', '-isysroot', sdkroot, ios_min]

[binaries]
c = '${CC_PATH}'
cpp = '${CXX_PATH}'
objc = '${CC_PATH}'
objcpp = '${CXX_PATH}'
ar = '${AR_PATH}'
strip = '${STRIP_PATH}'
pkg-config = 'pkg-config'

[built-in options]
c_args = common_flags
cpp_args = common_flags
objc_args = common_flags
objcpp_args = common_flags
c_link_args = common_flags
cpp_link_args = common_flags
objc_link_args = common_flags
objcpp_link_args = common_flags

[properties]
# iOS is a cross target; disable anything that tries to run target binaries.
needs_exe_wrapper = true
sys_root = sdkroot

[host_machine]
system = 'darwin'
subsystem = 'ios'
kernel = 'xnu'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
EOF

echo "[gen-cross-file] Wrote cross file to ${OUT}:"
echo "-------------------------------------------"
cat "${OUT}"
echo "-------------------------------------------"
